docker:
  image: "maven:3.3-jdk-8"
#install:
#  - "sudo apt-get install -y maven"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |-
      export newSnapshotVersion=`echo ${tag}-SNAPSHOT | perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e'`
      mvn clean verify
      mvn versions:set "-DnewVersion=${tag}"
      git commit -am "${tag}"
      mvn clean deploy -Prelease -PSubsteps.org --settings /home/r/settings.xml
      mvn versions:set "-DnewVersion=${newSnapshotVersion}"
      git commit -am "prepare next version"


#    mvn clean
#    mvn release:prepare release:perform -B -PSubsteps.org --settings /home/r/settings.xml

  commanders:
    - iantmoore


