docker:
  image: "maven:3.3-jdk-8"
#install:
#  - "sudo apt-get install -y maven"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script: |-
  echo " ******** NEW TAG : ${tag} ************"
  echo " ******** NExt TAG : ${nextVersion} ************"
#    mvn clean
#    mvn release:prepare release:perform -B -PSubsteps.org --settings /home/r/settings.xml
  commanders:
    - iantmoore

#      mvn clean verify
#      mvn versions:set "-DnewVersion=${tag}"
#      git commit -am "${tag}"
#      mvn clean deploy --settings /home/r/settings.xml
#      mvn versions:set "-DnewVersion=${nexttag}-SNAPSHOT"
#      git commit -am "prepare next version"
